volumes:
  postgres_data:

services:
  postgres-server:
    image: postgres:17.2
    container_name: ssp-postgres
    restart: always
    pull_policy: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ${PROJECT_DIR}/postgres/.env

  ssp:
    depends_on:
      postgres-server:
        condition: service_healthy

  api:
    depends_on:
      postgres-server:
        condition: service_healthy
