volumes:
  clickhouse_data:
  state_data:

x-mixins:
  clickhouse-image: &clickhouse-image
    image: clickhouse/clickhouse-server:24.5.1.1763

services:
  clickhouse-server:
    <<: *clickhouse-image
    container_name: ssp-clickhouse
    restart: always
    pull_policy: always
    healthcheck:
      test: ["CMD", "bash", "-c", "clickhouse-client --query \"SELECT value FROM system.settings WHERE name = 'readonly'\" | grep -q '0'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./clickhouse/config.xml:/etc/clickhouse-server/config.xml:ro"
      - "./clickhouse/conf.d:/etc/clickhouse-server/conf.d:ro"
      - clickhouse_data:/var/lib/clickhouse:cached
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    cpu_quota: 100000
    mem_limit: "2GB"

  clickhouse-init:
    <<: *clickhouse-image
    container_name: ssp-clickhouse-init
    pull_policy: always
    entrypoint: [ './migrations.sh' ]
    depends_on:
      clickhouse-server:
        condition: service_healthy
    volumes:
      - "./clickhouse/migrations.sh:/migrations.sh:ro"
      - "./clickhouse/migrations/stats:/migrations:ro"
      - "./clickhouse/migrations/stats-gen:/migrations-gen:ro"
      - "state_data:/state"
    environment:
      - REPLICATED=false

  ssp:
    depends_on:
      clickhouse-server:
        condition: service_healthy
      clickhouse-init:
        condition: service_started

  api:
    depends_on:
      clickhouse-server:
        condition: service_healthy
      clickhouse-init:
        condition: service_started
