volumes:
  state_data:

services:
  eventstream:
    image: geniusrabbit/eventstream:latest
    restart: always
    pull_policy: always
    depends_on: [redis, clickhouse-server]
    healthcheck:
      test: ["CMD", "/curl", "-f", "http://127.0.0.1:6060/health-check"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - eventstream/.env
    volumes:
      - ../eventstream.hcl:/config.hcl
    environment:
      - SERVER_PROFILE_MODE=net
      - SERVER_PROFILE_LISTEN=:6060

  ##############################################################################
  # SSP Server services
  ##############################################################################
  ssp:
    image: ghcr.io/sspserver/sspserver:latest
    container_name: ssp-server
    restart: always
    pull_policy: always
    command: ["sspserver"]
    env_file:
      - sspserver/.env
    ports:
      - "${SSP_SERVER_PORT:-8080}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    image: ghcr.io/sspserver/api:latest
    container_name: ssp-api
    restart: always
    pull_policy: always
    command: ["--run-migrations"]
    env_file:
      - api/.env
    ports:
      - "${SSP_API_PORT:-8081}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  control:
    image: ghcr.io/sspserver/control:latest
    container_name: ssp-control
    restart: always
    pull_policy: always
    env_file:
      - control/.env
    ports:
      - "${SSP_CONTROL_PORT:-8082}:3000"
    depends_on:
      - api

  ##############################################################################
  ## Web server
  ##############################################################################
  proxy:
    image: nginx:1.27
    container_name: ssp-webserver
    restart: always
    pull_policy: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    depends_on:
      - ssp
      - api
      - control
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
    environment:
      - NGINX_SSP_HOST=ssp
      - NGINX_SSP_PORT=8080
      - NGINX_SSP_PUBLIC_HOST=${SSPSERVER_AD_DOMAIN}
      - NGINX_API_HOST=api
      - NGINX_API_PORT=8080
      - NGINX_API_PUBLIC_HOST=${SSPSERVER_API_DOMAIN}
      - NGINX_CONTROL_HOST=control
      - NGINX_CONTROL_PORT=3000
      - NGINX_CONTROL_PUBLIC_HOST=${SSPSERVER_CONTROL_DOMAIN}
