volumes:
  state_data:

services:
  ssp:
    image: ghcr.io/sspserver/sspserver:latest
    restart: always
    pull_policy: always
    command: ["sspserver"]
    env_file:
      - ${PROJECT_DIR}/app-ssp/.env
    ports:
      - "${SSP_SERVER_PORT:-8080}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    image: ghcr.io/sspserver/api:latest
    restart: always
    pull_policy: always
    command: ["--run-migrations"]
    env_file:
      - ${PROJECT_DIR}/app-api/.env
    ports:
      - "${SSP_API_PORT:-8081}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  control:
    image: ghcr.io/sspserver/control:latest
    restart: always
    pull_policy: always
    env_file:
      - ${PROJECT_DIR}/app-control/.env
    ports:
      - "${SSP_CONTROL_PORT:-8082}:3000"
    depends_on:
      - api
      - ssp
