services:
  ##############################################################################
  # SSP Server services
  ssp:
    image: sspserver/sspserver:latest
    ports:
      - "8080:8080"
  api:
    image: sspserver/api:latest
    ports:
      - "8081:8081"
